"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/building_a_plugin/guides.html#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""
import numpy as np

from typing import TYPE_CHECKING, Optional, Tuple, Any, List

from magicgui import widgets
from magicgui.widgets import Container, create_widget

if TYPE_CHECKING:
    import napari


class PredictLabels(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer
        self._image_layer_combo = create_widget(
            label="Image", annotation="napari.layers.Image"
        )
        self._predict_btn = widgets.PushButton(text="Predict Labels")
        self._predict_btn.clicked.connect(self._request_prediction)

        self.extend(
            [
                self._image_layer_combo,
                self._predict_btn
            ]
        )
    
    def _request_prediction(self):
        image_layer = self._image_layer_combo.value
        if image_layer is None:
            raise(ValueError("Select an image layer first."))
        
        shape = image_layer.data.shape
        labels = np.random.randint(0, 4, size=shape, dtype=np.uint8) 
        
        name = image_layer.name + "_labels"
        if name in self._viewer.layers:
            self._viewer.layers[name].data += labels
        
        self._viewer.add_labels(labels, name=name)
        
